name: Build Failure Notification

on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed

jobs:
  notify-failure:
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Get workflow run info
        id: workflow_info
        run: |
          echo "WORKFLOW_RUN_ID=${{ github.event.workflow_run.id }}" >> $GITHUB_ENV
          echo "WORKFLOW_HEAD_SHA=${{ github.event.workflow_run.head_sha }}" >> $GITHUB_ENV
          echo "WORKFLOW_HEAD_BRANCH=${{ github.event.workflow_run.head_branch }}" >> $GITHUB_ENV

      - name: Get commit info
        id: commit_info
        run: |
          # Get commit message and author info using GitHub API
          COMMIT_INFO=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/commits/${{ env.WORKFLOW_HEAD_SHA }}")
          
          COMMIT_MESSAGE=$(echo "$COMMIT_INFO" | jq -r '.commit.message' | head -n1)
          AUTHOR_NAME=$(echo "$COMMIT_INFO" | jq -r '.commit.author.name')
          AUTHOR_LOGIN=$(echo "$COMMIT_INFO" | jq -r '.author.login // .commit.author.name')
          
          echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV
          echo "AUTHOR_NAME=$AUTHOR_NAME" >> $GITHUB_ENV
          echo "AUTHOR_LOGIN=$AUTHOR_LOGIN" >> $GITHUB_ENV

      - name: Discord Failure Notification
        uses: satak/webrequest-action@master
        with:
          url: ${{ secrets.DISCORD_WEBHOOK_STAFF }}
          method: POST
          payload: |
            {
              "content": "<@&1312808018483613726> \n**BUILD FAILED**",
              "embeds": [{
                "title": "[${{ github.repository }}:${{ env.WORKFLOW_HEAD_BRANCH }}] - Build Failed",
                "author": {
                  "name": "${{ env.AUTHOR_NAME }}",
                  "url": "https://github.com/${{ env.AUTHOR_LOGIN }}",
                  "icon_url": "https://github.com/${{ env.AUTHOR_LOGIN }}.png"
                },
                "description": "**Failed Commit:** `${{ env.COMMIT_MESSAGE }}`\n\n[View Failed Workflow Run](https://github.com/${{ github.repository }}/actions/runs/${{ env.WORKFLOW_RUN_ID }})\n[View Commit](https://github.com/${{ github.repository }}/commit/${{ env.WORKFLOW_HEAD_SHA }})",
                "color": 15158332,
                "fields": [
                  {
                    "name": "Branch",
                    "value": "`${{ env.WORKFLOW_HEAD_BRANCH }}`",
                    "inline": true
                  },
                  {
                    "name": "Workflow",
                    "value": "build",
                    "inline": true
                  }
                ],
                "timestamp": "${{ github.event.workflow_run.updated_at }}"
              }]
            }