name: build

on:
  push:
    branches:
      - main

jobs:
  notify:
    if: "!contains(env.COMMIT_MESSAGE, '{skip_discord}')"
    runs-on: ubuntu-22.04
    steps:
      - name: Get branch name
        id: get_branch_name
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Make the commit message compatible with JSON
        run: |
          # Escape the commit message for JSON
          COMMIT_MESSAGE=$(echo -n "${{ github.event.head_commit.message }}" | sed 's/%0A/\\n/g' | jq -s -Rr @json)
          COMMIT_MESSAGE=${COMMIT_MESSAGE:1:-1}
          echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV

      - name: Discord Message
        uses: satak/webrequest-action@master
        with:
          url: ${{ secrets.DISCORD_WEBHOOK }}
          method: POST
          payload: '{ "content": "", "embeds": [{ "title": "[${{ github.repository }}:${{ env.BRANCH_NAME }}] - new commit", "author": {"name": "${{ github.event.head_commit.author.name}}","url": "https://github.com/${{ github.event.head_commit.author.name}}","icon_url": "https://github.com/${{ github.event.head_commit.author.name}}.png"},"description": "```Commit Message:\n\n${{ env.COMMIT_MESSAGE }}```", "url": "https://github.com/${{ github.repository }}/commit/${{ github.sha }}", "color": 5315202 }] }'

  build:
    if: "!contains(env.COMMIT_MESSAGE, '{skip_build}')"
    strategy:
      matrix:
        minecraft_version: [1.21, 1.21.2, 1.21.4, 1.21.5, 1.21.6]
    runs-on: ubuntu-22.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: setup jdk 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'microsoft'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
        
      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts-${{ matrix.minecraft_version }}
          path: versions/${{ matrix.minecraft_version }}/build/libs/