name: dev_build

on:
  workflow_dispatch:
    inputs:
      version_name:
        description: 'Version Name'
        required: true
        default: 'dev-version'
        type: string
      full_changelog:
        description: 'Full Changelog Link'
        required: true
        default: 'https://github.com/Mat0u5/LifeSeries'
        type: string
      changelog:
        description: 'Shortened Changelog'
        required: true
        default: 'No changelog provided'
        type: string

jobs:
  release:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: setup jdk 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'microsoft'

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: build
        run: ./gradlew build

      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Built JARs
          path: |
            ./versions/**/build/libs/*.jar

      - name: Filter non-source JAR files
        id: filtered_jars
        run: |
          jars=$(find ./versions/**/build/libs/ -type f -name "*.jar" ! -name "*-sources.jar")
          echo "jar_files<<EOF" >> $GITHUB_OUTPUT
          echo "$jars" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Generate Version Tag
        id: version
        run: |
          # Generate a version based on current date and commit hash
          VERSION="$(echo ${{ github.event.inputs.version_name }})"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Generated version: $VERSION"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release with JARs
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ steps.version.outputs.version }}
          name: Dev build:${{ steps.version.outputs.version }}
          body: |
            Changelog since the latest full release on [Modrinth](https://modrinth.com/mod/life-series):
            ```
            ${{ github.event.inputs.changelog }}
            ```
            [Click here to open the **full changelog**](${{ github.event.inputs.full_changelog }})
          draft: false
          prerelease: true
          files: |
            ${{ steps.filtered_jars.outputs.jar_files }}

      - name: Discord Message
        uses: satak/webrequest-action@master
        with:
          url: ${{ secrets.DISCORD_WEBHOOK_DEVBUILDS }}
          method: POST
          payload: '{ "content": "<@&1312808018483613726>\n## [Developer version `${{ github.event.inputs.version_name }}` is out!](https://github.com/Mat0u5/LifeSeries/releases/tag/${{ github.event.inputs.version_name }})", "embeds": [{"author": {"name": "Mat0u5","url": "https://github.com/Mat0u5","icon_url": "https://github.com/Mat0u5.png"},"description": "\nChangelog since the latest full release on [Modrinth](https://modrinth.com/mod/life-series):\n```\n${{ github.event.inputs.changelog }}```\n[Click here to open the **full changelog**](${{ github.event.inputs.full_changelog }})", "color": 5315202 }] }'